name: Sync HA Version

on:
  workflow_dispatch:
  push:
    paths:
      - requirements.txt
  pull_request:
    paths:
      - requirements.txt

permissions:
  contents: write
  pull-requests: write

jobs:
  hassfest: # https://developers.home-assistant.io/blog/2020/04/16/hassfest
    name: Hassfest validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5.0.0

      - name: Extract Home Assistant version from requirements.txt
        id: ha_version
        run: |
          HA_VERSION=$(grep '^homeassistant==' requirements.txt | sed 's/homeassistant==//')
          echo "ha_version=$HA_VERSION" >> $GITHUB_OUTPUT

      - name: Update hacs.json with Home Assistant version
        run: |
          jq --arg ver "${{ steps.ha_version.outputs.ha_version }}" '.homeassistant = $ver' hacs.json > hacs.json.tmp && mv hacs.json.tmp hacs.json

      - name: Create Pull Request
        if: startsWith(github.ref, 'refs/tags/v')
        uses: peter-evans/create-pull-request@v7
        id: cpr
        with:
          commit-message: Update hacs.json Home Assistant version to ${{ steps.ha_version.outputs.ha_version }}
          signoff: false
          branch: pr-update-hacs-v${{ steps.ha_version.outputs.ha_version }}
          delete-branch: false
          title: Update tools v${{ steps.ha_version.outputs.ha_version }} docs
          branch-suffix: short-commit-hash
          body: |
            Automatic update of hacs.json Home Assistant version to ${{ steps.ha_version.outputs.ha_version }}.
          draft: false
          add-paths:
            hacs.json